name: johbong_pro
description: Official Johbong Network Management App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  pdf: ^3.10.8
  printing: ^5.11.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  router_os_client: ^2.0.0
  syncfusion_flutter_datepicker: ^21.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - logo.png
